### ISSUE TITLE
ImportError: csbdeep only supports tensorflow < 2 for now (installed tensorflow version: 2.3.0)

### ISSUE THREAD

**Issue by Mrc010** [juglab/DenoiSeg#44]
Hi there,

I had just followed the [installation instructions](https://github.com/juglab/DenoiSeg#installation), which include `pip install tensorflow==2.3 `. Then I chose [option 1](https://github.com/juglab/DenoiSeg#option-1-pip-current-stable-release).
But when trying out an [example notebook](https://github.com/juglab/DenoiSeg/blob/master/examples/DenoiSeg_2D/FlyWing_DenoiSeg_Example.ipynb), I got the error message `csbdeep only supports tensorflow < 2 for now (installed tensorflow version: 2.3.0)`. I'm confused now.

Edit: Solved the issue by `pip uninstall tensorflow`, `pip install tensorflow-gpu==1.15.0`. This seemed only to be required for  I thus chose to proceed with [option 2](https://github.com/juglab/DenoiSeg#option-2-git-clone-and-install-from-sources-current-master-branch-version).
Also, because an error was thrown that `cudart64_100.dll` was missing, I had to `conda install cudatoolkit==10.0 cudnn` .

**Comment by jdeschamps** [comment]
Turns out we updated the repository but did not roll out a new version, which was a mistake on our part.

We recently started caring a bit more for the repo, and now there is a new version compatible with TensorFlow > 2.7
